//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Attend
    {
        public decimal Emp_Att_Id { get; set; }
        public string Emp_Att_Code { get; set; }
        public Nullable<System.DateTime> Emp_Att_Date { get; set; }
        public Nullable<int> Emp_Att_Houer { get; set; }
        public Nullable<bool> Emp_Att_State { get; set; }
        public string Emp_Att_Note { get; set; }
        public Nullable<decimal> Emp_Id { get; set; }
        public Nullable<decimal> Emp_Att_D_Id { get; set; }
    
        public virtual T_Attend_Day T_Attend_Day { get; set; }
        public virtual T_Emploee T_Emploee { get; set; }
    }
}
