//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Attend_Month
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Attend_Month()
        {
            this.T_Attend_Day = new HashSet<T_Attend_Day>();
        }
    
        public decimal Emp_Att_M_Id { get; set; }
        public string Emp_Att_M_Code { get; set; }
        public Nullable<System.DateTime> Emp_Att_M_Date { get; set; }
        public Nullable<decimal> Emp_Att_M_Month_Num { get; set; }
        public string Emp_Att_M_Month_Name { get; set; }
        public Nullable<int> Emp_Att_M_Day_Count { get; set; }
        public Nullable<bool> Emp_Att_M_State { get; set; }
        public string Emp_Att_M_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Attend_Day> T_Attend_Day { get; set; }
    }
}
