//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Attend_Day
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Attend_Day()
        {
            this.T_Attend = new HashSet<T_Attend>();
        }
    
        public decimal Emp_Att_D_Id { get; set; }
        public string Emp_Att_D_Code { get; set; }
        public Nullable<System.DateTime> Emp_Att_D_Date { get; set; }
        public string Emp_Att_D_Day { get; set; }
        public Nullable<bool> Emp_Att_D_State { get; set; }
        public string Emp_Att_D_Note { get; set; }
        public Nullable<decimal> Emp_Att_M_Id { get; set; }
    
        public virtual T_Attend_Month T_Attend_Month { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Attend> T_Attend { get; set; }
    }
}
