//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Customer_Invoice()
        {
            this.T_Customer_Bill = new HashSet<T_Customer_Bill>();
        }
    
        public decimal Inv_Id { get; set; }
        public string Inv_Code { get; set; }
        public Nullable<System.DateTime> Inv_Date { get; set; }
        public Nullable<System.TimeSpan> Inv_Time { get; set; }
        public Nullable<decimal> Inv_Price { get; set; }
        public Nullable<decimal> Inv_Discount { get; set; }
        public Nullable<decimal> Inv_Total { get; set; }
        public Nullable<bool> Inv_State { get; set; }
        public string Inv_Note { get; set; }
        public Nullable<decimal> Con_Id { get; set; }
        public Nullable<decimal> Cust_Id { get; set; }
    
        public virtual T_Customer T_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Customer_Bill> T_Customer_Bill { get; set; }
        public virtual T_Customer_Contract T_Customer_Contract { get; set; }
    }
}
