//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer_Companey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Customer_Companey()
        {
            this.T_Customer_Contract = new HashSet<T_Customer_Contract>();
        }
    
        public decimal Cust_Com_Id { get; set; }
        public string Cust_Com_Code { get; set; }
        public string Cust_Com_place { get; set; }
        public string Cust_Com_Name { get; set; }
        public string Cust_Com_Time { get; set; }
        public string Cust_Com_Major { get; set; }
        public Nullable<bool> Cust_Com_State { get; set; }
        public string Cust_Com_Note { get; set; }
        public Nullable<decimal> Cust_Id { get; set; }
    
        public virtual T_Customer T_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Customer_Contract> T_Customer_Contract { get; set; }
    }
}
