//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Customer_Contract()
        {
            this.T_Customer_Invoice = new HashSet<T_Customer_Invoice>();
        }
    
        public decimal Con_Id { get; set; }
        public string Con_Code { get; set; }
        public string Con_Name { get; set; }
        public Nullable<System.DateTime> Con_Date { get; set; }
        public Nullable<System.DateTime> Con_S_Date { get; set; }
        public Nullable<System.DateTime> Con_E_Date { get; set; }
        public Nullable<decimal> Con_ { get; set; }
        public Nullable<int> Con_Emp_Num { get; set; }
        public Nullable<decimal> Con_emp_Value { get; set; }
        public Nullable<bool> Con_State { get; set; }
        public string Con_Note { get; set; }
        public Nullable<decimal> Cust_Id { get; set; }
        public Nullable<decimal> Cust_Com_Id { get; set; }
    
        public virtual T_Customer T_Customer { get; set; }
        public virtual T_Customer_Companey T_Customer_Companey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Customer_Invoice> T_Customer_Invoice { get; set; }
    }
}
