//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer_Bill
    {
        public decimal bill_Id { get; set; }
        public string bill_Code { get; set; }
        public string bill_Text { get; set; }
        public Nullable<System.DateTime> bill_Date { get; set; }
        public Nullable<System.TimeSpan> bill_Time { get; set; }
        public Nullable<decimal> bill_Price { get; set; }
        public Nullable<bool> bill_State { get; set; }
        public string bill_Note { get; set; }
        public Nullable<decimal> Inv_Id { get; set; }
    
        public virtual T_Customer_Invoice T_Customer_Invoice { get; set; }
    }
}
