//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Customer()
        {
            this.T_Customer_Contract = new HashSet<T_Customer_Contract>();
            this.T_Customer_Companey = new HashSet<T_Customer_Companey>();
            this.T_Customer_Invoice = new HashSet<T_Customer_Invoice>();
        }
    
        public decimal Cust_Id { get; set; }
        public string Cust_Code { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Mobile { get; set; }
        public string Cust_Phone { get; set; }
        public string Cust_Fax { get; set; }
        public string Cust_Email { get; set; }
        public string Cust_Address { get; set; }
        public Nullable<bool> Cust_State { get; set; }
        public string Cust_Note { get; set; }
        public Nullable<decimal> Company_Id { get; set; }
    
        public virtual T_Companey T_Companey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Customer_Contract> T_Customer_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Customer_Companey> T_Customer_Companey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Customer_Invoice> T_Customer_Invoice { get; set; }
    }
}
