//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Employee_Experiance
    {
        public decimal Emp_Exp_Id { get; set; }
        public string Emp_Exp_Code { get; set; }
        public string Emp_Exp_Name { get; set; }
        public Nullable<System.DateTime> Emp_Exp_Date { get; set; }
        public string Emp_Exp_Length { get; set; }
        public string Emp_Exp_Adress { get; set; }
        public string Emp_Exp_Major { get; set; }
        public Nullable<bool> Emp_Exp_State { get; set; }
        public string Emp_Exp_note { get; set; }
        public decimal Emp_Id { get; set; }
    
        public virtual T_Emploee T_Emploee { get; set; }
    }
}
