//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Employee_Retriment
    {
        public decimal Emp_Re_Id { get; set; }
        public string Emp_Re_Code { get; set; }
        public string Emp_Re_Name { get; set; }
        public Nullable<System.DateTime> Emp_Re_Date { get; set; }
        public string Emp_Re_Resone { get; set; }
        public Nullable<decimal> Emp_Re_Salary { get; set; }
        public Nullable<bool> Emp_Re_State { get; set; }
        public string Emp_Re_Note { get; set; }
        public Nullable<decimal> Emp_Id { get; set; }
    
        public virtual T_Emploee T_Emploee { get; set; }
    }
}
