//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Emploee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Emploee()
        {
            this.T_Salarey_Month = new HashSet<T_Salarey_Month>();
            this.T_Employee_Certificate = new HashSet<T_Employee_Certificate>();
            this.T_Employee_Experiance = new HashSet<T_Employee_Experiance>();
            this.T_Employee_File = new HashSet<T_Employee_File>();
            this.T_Employee_Retriment = new HashSet<T_Employee_Retriment>();
            this.T_Employee_Social = new HashSet<T_Employee_Social>();
            this.T_Attend = new HashSet<T_Attend>();
        }
    
        public decimal Emp_Id { get; set; }
        public string Emp_Code { get; set; }
        public string Emp_F_Name { get; set; }
        public string Emp_L_Name { get; set; }
        public string Emp_Nation_num { get; set; }
        public Nullable<System.DateTime> Emp_B_Date { get; set; }
        public Nullable<int> Emp_Age { get; set; }
        public Nullable<int> Emp_Gender { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_Phone { get; set; }
        public string Emp_Mobile { get; set; }
        public string Emp_Maritial { get; set; }
        public Nullable<bool> Emp_State { get; set; }
        public string Emp_Note { get; set; }
        public Nullable<decimal> Emp_St_Id { get; set; }
        public Nullable<decimal> Emp_Mp_Id { get; set; }
        public Nullable<decimal> Company_Id { get; set; }
        public Nullable<System.DateTime> Emp_S_Date { get; set; }
    
        public virtual T_Companey T_Companey { get; set; }
        public virtual T_Employee_Map T_Employee_Map { get; set; }
        public virtual T_Employee_State T_Employee_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Salarey_Month> T_Salarey_Month { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Employee_Certificate> T_Employee_Certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Employee_Experiance> T_Employee_Experiance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Employee_File> T_Employee_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Employee_Retriment> T_Employee_Retriment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Employee_Social> T_Employee_Social { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Attend> T_Attend { get; set; }
    }
}
