//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Employee_Map
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Employee_Map()
        {
            this.T_Emploee = new HashSet<T_Emploee>();
            this.T_Salary_Master = new HashSet<T_Salary_Master>();
        }
    
        public decimal Emp_Mp_Id { get; set; }
        public string Emp_Mp_Code { get; set; }
        public string Emp_Mp_Class { get; set; }
        public string Emp_Mp_Level { get; set; }
        public Nullable<decimal> Emp_Mp_Bonas { get; set; }
        public Nullable<decimal> Emp_Mp_Blus { get; set; }
        public Nullable<decimal> Emp_Mp_Year { get; set; }
        public Nullable<decimal> Emp_Mp_Salary { get; set; }
        public Nullable<decimal> Emp_Mp_Single_Bons { get; set; }
        public Nullable<decimal> Emp_Mp_Marrid_Bons { get; set; }
        public Nullable<decimal> Company_Id { get; set; }
    
        public virtual T_Companey T_Companey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Emploee> T_Emploee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Salary_Master> T_Salary_Master { get; set; }
    }
}
