//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Employee_Social
    {
        public decimal Emp_Ss_ID { get; set; }
        public string Emp_Ss_Code { get; set; }
        public string Emp_Ss_Number { get; set; }
        public Nullable<System.DateTime> Emp_Ss_Date { get; set; }
        public Nullable<System.DateTime> Emp_Ss_End_date { get; set; }
        public Nullable<decimal> Emp_Ss_Salarey { get; set; }
        public Nullable<decimal> Emp_Ss_Emp { get; set; }
        public Nullable<decimal> Emp_Ss_Company { get; set; }
        public Nullable<bool> Emp_Ss_State { get; set; }
        public string Emp_Ss_Note { get; set; }
        public Nullable<decimal> Emp_Id { get; set; }
    
        public virtual T_Emploee T_Emploee { get; set; }
    }
}
