//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Employee_State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Employee_State()
        {
            this.T_Emploee = new HashSet<T_Emploee>();
        }
    
        public decimal Emp_St_Id { get; set; }
        public string Emp_St_Code { get; set; }
        public string Emp_St_Name { get; set; }
        public Nullable<bool> Emp_St_State { get; set; }
        public string Emp_St_Note { get; set; }
        public Nullable<decimal> Company_Id { get; set; }
    
        public virtual T_Companey T_Companey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Emploee> T_Emploee { get; set; }
    }
}
