//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Employee_File
    {
        public decimal Emp_F_Id { get; set; }
        public string Emp_F_Code { get; set; }
        public string Emp_F_Name { get; set; }
        public string Emp_F_Type { get; set; }
        public string Emp_F_Path { get; set; }
        public Nullable<bool> Emp_F_State { get; set; }
        public string Emp_F_Note { get; set; }
        public Nullable<decimal> Emp_Id { get; set; }
    
        public virtual T_Emploee T_Emploee { get; set; }
    }
}
