//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Salarey_Month
    {
        public decimal Emp_Mnth_Sal_Id { get; set; }
        public string Emp_Mnth_Sal_Code { get; set; }
        public string Emp_Mnth_Sal_Name { get; set; }
        public Nullable<System.DateTime> Emp_Mnth_Sal_Date { get; set; }
        public Nullable<decimal> Emp_Mnth_Sal_Salary { get; set; }
        public Nullable<decimal> Emp_Mnth_Sal_Bonas { get; set; }
        public Nullable<decimal> Emp_Mnth_Sal_Minose { get; set; }
        public Nullable<decimal> Emp_Mnth_Sal_SS_Minous { get; set; }
        public Nullable<decimal> Emp_Mnth_Sal_Total { get; set; }
        public Nullable<bool> Emp_Mnth_Sal_State { get; set; }
        public string Emp_Mnth_Sal_Note { get; set; }
        public Nullable<decimal> Emp_Id { get; set; }
        public Nullable<decimal> Emp_Sal_Id { get; set; }
        public Nullable<decimal> Emp_Mnth_Sal_Day_Price { get; set; }
        public Nullable<int> Emp_Mnth_Sal_Bonas_Day { get; set; }
        public Nullable<int> Emp_Mnth_Sal_Minous_Day { get; set; }
        public Nullable<decimal> Emp_Mnth_Sal_Adv { get; set; }
        public Nullable<decimal> Emp_Mnth_Sal_Debt { get; set; }
    
        public virtual T_Emploee T_Emploee { get; set; }
        public virtual T_Salary_Master T_Salary_Master { get; set; }
    }
}
