//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users
    {
        public decimal User_Id { get; set; }
        public string User_Code { get; set; }
        public string User_Name { get; set; }
        public string User_Password { get; set; }
        public Nullable<bool> User_State { get; set; }
        public string User_Note { get; set; }
        public Nullable<decimal> User_T_Id { get; set; }
        public Nullable<decimal> Comp_Id { get; set; }
    
        public virtual T_Companey T_Companey { get; set; }
        public virtual T_User_Type T_User_Type { get; set; }
    }
}
