//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Emp_Month_Atend_Salarey
    {
        public decimal Emp_Att_M_Id { get; set; }
        public string Emp_Att_M_Month_Name { get; set; }
        public Nullable<int> yeaar { get; set; }
        public Nullable<int> Emp_Att_M_Day_Count { get; set; }
        public decimal Emp_Id { get; set; }
        public string emp_name { get; set; }
        public Nullable<int> total_hours { get; set; }
    }
}
